Controllers/ApisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApiBankBackBone.Data;
using ApiBankBackBone.Models.Apis;
using AutoMapper;

namespace ApiBankBackBone.Controllers
{
    public class ApisController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public ApisController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: Apis
        public async Task<IActionResult> Index()
        {
            return View(await _context.Apis.ToListAsync());
        }

        // GET: Apis/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var api = await _context.Apis.FirstOrDefaultAsync(m => m.Id == id);

            if (api == null)
            {
                return NotFound();
            }

            var result = _mapper.Map<ApiDto>(api);
            result.Methods = await _context.Methods.Where(m => m.ApiId == id).ToListAsync() ?? new List<Method>();

            return View(result);
        }

        // GET: Apis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Apis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,IsFree,AccessCost,MonthlyCost,AdditionalAccessRules,License")] Api api)
        {
            if (ModelState.IsValid)
            {
                api.Id = Guid.NewGuid();
                _context.Add(api);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(api);
        }

        // GET: Apis/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var api = await _context.Apis.FindAsync(id);
            if (api == null)
            {
                return NotFound();
            }
            return View(api);
        }

        // POST: Apis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Description,IsFree,AccessCost,MonthlyCost,AdditionalAccessRules,License")] Api api)
        {
            if (id != api.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(api);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApiExists(api.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(api);
        }

        // GET: Apis/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var api = await _context.Apis
                .FirstOrDefaultAsync(m => m.Id == id);
            if (api == null)
            {
                return NotFound();
            }

            return View(api);
        }

        // POST: Apis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var api = await _context.Apis.FindAsync(id);
            _context.Apis.Remove(api);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApiExists(Guid id)
        {
            return _context.Apis.Any(e => e.Id == id);
        }
    }
}

Controllers/ExternalApiController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ApiBankBackBone.Data;
using ApiBankBackBone.Helpers;
using ApiBankBackBone.Helpers.Pagination;
using ApiBankBackBone.Models.Apis;
using ApiBankBackBone.Models.Common.Api;
using AutoMapper;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PagedList.Core;

namespace ApiBankBackBone.Controllers
{
	public class ExternalApiController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly IMapper _mapper;

		public ExternalApiController(ApplicationDbContext context, IMapper mapper)
		{
			_context = context;
			_mapper = mapper;
		}

		[EnableCors("LocalApi")]
		public async Task<string> GetApis(int page = 1, int size = 10, string filter = null)
		{
			ApiResult result;

			try
			{
				var paginationData = await GetApisForPagination(page, size, filter);
				var methods = await GetMethods(paginationData.Item1);

				var listOfDto = new List<ApiDto>();
				foreach (var api in paginationData.Item1)
				{
					var dto = _mapper.Map<ApiDto>(api);
					if (methods.TryGetValue(dto.Id, out var concreteMethods))
					{
						dto.Methods = concreteMethods;
					}

					listOfDto.Add(dto);
				}

				var paginationDto = new SimplePaginationDto<ApiDto>(listOfDto, page, size, paginationData.Item2, filter);
				result = ApiResult.SucceedResult<SimplePaginationDto<ApiDto>>(paginationDto);
			}
			catch (Exception e)
			{
				result = ApiResult.ErrorResult("Api fetching error 1", $"{e.Message} - {e.InnerException} - {e.StackTrace}");
			}
			
			return JsonConvert.SerializeObject(result);
		}

		[EnableCors("LocalApi")]
		[HttpDelete]
		public async Task<string> Delete(Guid id)
		{
			ApiResult result;

			try
			{
				var api = await _context.Apis.FindAsync(id);
				_context.Remove(api);
				await _context.SaveChangesAsync();

				var keyValue = new Dictionary<string, Guid> {{"deletedId", id}};
				result = ApiResult.SucceedResult<Dictionary<string, Guid>>(keyValue);
			}
			catch (Exception e)
			{
				result = ApiResult.ErrorResult("Api deleting error", $"{e.Message} - {e.InnerException} - {e.StackTrace}");
			}

			return JsonConvert.SerializeObject(result);
		}

		[EnableCors("LocalApi")]
		[HttpPost]
		public async Task<string> Create()
		{
			ApiResult result;

			try
			{
				using StreamReader reader = new StreamReader(Request.Body, Encoding.UTF8);
				var body = await reader.ReadToEndAsync();

				var api = JsonConvert.DeserializeObject<Api>(body, new JsonSerializerSettings
				{
					NullValueHandling = NullValueHandling.Ignore
				});

				if (api != null)
				{
					api.Id = Guid.NewGuid();
					await _context.Apis.AddAsync(api);
					await _context.SaveChangesAsync();

					result = ApiResult.SucceedResult<Api>(api);
				}
				else
				{
					result = ApiResult.ErrorResult("Api creation error 1", "api is not serialized");
				}
			}
			catch (Exception e)
			{
				result = ApiResult.ErrorResult("Api creation error 2", $"{e.Message} - {e.InnerException} - {e.StackTrace}");
			}

			return JsonConvert.SerializeObject(result);
		}

		[HttpGet]
		public async Task<string> Add10Apis()
		{
			ApiResult result;
			var apis = new List<Api>();

			try
			{
				foreach (var index in Enumerable.Range(1, 11))
				{
					var api = new Api();
					var random = new Random();
					var temp = random.Next(0, 999);

					api.Id = Guid.NewGuid();

					var isOdd = temp % 2 == 0;
					var partOfName = isOdd ? "Odd api, by crazy maniacs." : "Vovel api, beauty is here!";
					api.Name = $"{index} Api. {partOfName}";

					if (isOdd)
					{
						api.IsFree = true;
					}
					else
					{
						api.IsFree = false;
						api.AccessCost = random.Next(1, 10000);
						if (temp % 8 == 0)
						{
							api.MonthlyCost = random.Next(1, 10000);
						}
					}

					api.License = $"APACHIK {index}.0";
					api.AdditionalAccessRules = "do nothing";
					api.Description = StringHelper.RandomString(random.Next(25, 1589));

					await _context.Apis.AddAsync(api);
					await _context.SaveChangesAsync();

					apis.Add(api);
				}

				result = ApiResult.SucceedResult<List<Api>>(apis);
			}
			catch (Exception e)
			{
				result = ApiResult.ErrorResult("Api creation error 2", $"{e.Message} - {e.InnerException} - {e.StackTrace}");
			}

			return JsonConvert.SerializeObject(result);
		}

		private async Task<Tuple<List<Api>, int>> GetApisForPagination(int page, int pageSize, string filter)
		{
			var rawApis = string.IsNullOrEmpty(filter)
				? _context.Apis
				: _context.Apis.Where(x => EF.Functions.Like(x.Name, $"%{filter.ToLower()}%")
				                           || EF.Functions.Like(x.Description, $"%{filter.ToLower()}%")
				                           || EF.Functions.Like(x.License, $"%{filter.ToLower()}%")
				                           || EF.Functions.Like(x.AdditionalAccessRules, $"%{filter.ToLower()}%"));

			var countToSkip = page == 1 ? 0 : ((page - 1) * pageSize);
			var totalCount = await rawApis.CountAsync();
			var apis = await rawApis.Skip(countToSkip).Take(pageSize).ToListAsync();

			return new Tuple<List<Api>, int>(apis, totalCount);
		}

		private async Task<Dictionary<Guid, Method[]>> GetMethods(IEnumerable<Api> apis)
		{
			var apiIds = apis.Select(x => x.Id);

			return (await _context.Methods.Where(x => apiIds.Contains(x.ApiId)).ToListAsync())
				.GroupBy(x => x.ApiId)
				.ToDictionary(x => x.Key, x => x.ToArray());
		}
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApiBankBackBone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ApiBankBackBone</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apis" asp-action="Index">Apis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExternalApi" asp-action="GetApis">Get apis json</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExternalApi" asp-action="Add10Apis">Add 10 ones</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ApiBankBackBone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>